# Gazebo controller configuration for the tactile matrix sensors.
# 
# 2023.05.02 - updated for Gazebo 11.11 with ROS noetic
#
# (C) 2023 fnh, hendrich@informatik.uni-hamburg.de

# for now, no namespace here...

# each sensor cell is modeled using one joint. So we need to publish
# joint states from Gazebo in order to get a full TF tree for the rest
# of ROS. Publishing rate is a compromise between latency and bandwidth.
#
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100


# example position (joint trajectory) controller for a single
# tactile sensor cell. Add joints as needed for linear arrays
# and matrix sensors:
#
tactile_sensor_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - tactile_cell_sensor_joint
  gains:
    tactile_cell_sensor_joint: { p: 100, d: 0.0, i: 1.0, i_clamp: 10 }
  joint_trajectory_action_node:
    joints:
      - tactile_cell_sensor_joint
    constraints:
      goal_time: 0.2


